### ISSUE TITLE
Error during installation CFD Module and DSMC

### ISSUE THREAD

**Issue by THE-NAME** [vincentcasseau/hyStrath#104]
HI vincentcassau, There are such errors when installing  modules.

[Uploading logInstall-CFD.txt…]()

**Comment by THE-NAME** [comment]
Yes, I'm using OF1706. After ask the question, I re-install the CFD module, and success.
I used command "./install.sh" instead of  "./install.sh NUMPROCS 2>/DEV/NULL".
My ubuntu system is virtual and running.
Thanks your reply.

Besides, I have a question.
When I test the case "Blunted cone", I change the numberOfSubdomains to 6. I use command "./Allrun 6". 
Whether command "./Allrun 6" causes command "gnuplot gnuplot/monitorResiduals" to be invalid?

**Comment by vincentcasseau** [comment]
_I used command "./install.sh" instead of "./install.sh NUMPROCS 2>/DEV/NULL"._
In your first attempt, had you replaced NUMPROCS with a number?

_When I test the case "Blunted cone", I change the numberOfSubdomains to 6. I use command "./Allrun 6"._
That's fine.

_Whether command "./Allrun 6" causes command "gnuplot gnuplot/monitorResiduals" to be invalid?_
No, these commands are unrelated.

**Comment by THE-NAME** [comment]
Thanks for your reply. I had not replaced NUMPROCS with a number.

I noticed that during the parallel computation, six Process folders were generated. At the end of calculation, there is only floder t=0.0002s. However, single-threaded calculations can hold folders for more times. I wonder if there is a way for parallel computing to store instantaneous results for more times.

**Comment by vincentcasseau** [comment]
Please have a look at what ./Allrun does, only the latest folder is reconstructed.

**Comment by THE-NAME** [comment]
Dr Vincent,

Thank you for your guidance. I think I know how to do it.

Best wishes,
wang
