### ISSUE TITLE
IO error with vibrationalEnergy

### ISSUE THREAD

**Issue by onurpaca** [vincentcasseau/hyStrath#2]
Dear Vincent,

When I turn on all the fields in constant/hTCProperties in mixtureOutputs section I get the following error while reconstructPar in parallel and foamToVTK in serial: 

    --> FOAM FATAL IO ERROR: 

    Cannot find 'value' entry on patch outlet of field e in file "/home/opaca/hy2Foam_tutorial_run/hyStrath/rotorbit_tutorials/wedge_ver6/1.2000000000e-08/e"
    which is required to set the values of the generic patch field.
    (Actual type gradient2Energy)

    Please add the 'value' entry to the write function of the user-defined boundary-condition
    file: /home/opaca/hy2Foam_tutorial_run/hyStrath/rotorbit_tutorials/wedge_ver6/1.2000000000e-08/e.boundaryField.outlet from line 8557 to line 8558.

    From function genericFvPatchField<Type>::genericFvPatchField(const fvPatch&, const Field<Type>&, const dictionary&)
    in file genericFvPatchField/genericFvPatchField.C at line 71.
    FOAM exiting

The reason I want to accomplish this is to map the solution from a coarse mesh to a finer mesh as initial condition, but to do this I need the Tv field in the solution file. So, I'm planning to use the e and zeta fields to get Tv. Do you have any recommendation to resolve this?

Thanks,
Onur

P.S This is a case that I generated based on the cylinderReactingMach20 case.

**Comment by vincentcasseau** [comment]
Hi Onur,

I remember seeing this error before. The _reconstructPar_ utility does not cope well the hard-coded (present in the _src/_ folder rather than the solver folder) boundary conditions for energy. I didn't try to solve the issue. After I have had a look at the decomposed energy fields, I deleted them and reconstruct the case.

There is one thing I don't understand. Why would you need energy and zeta to construct the _Tv_ field. There should be a way to get _Tv_ printed directly.

If you have one molecule in your flow, then you could duplicate _Tv mol_ into _Tv_.
If you have two or more, then you should activate [the _hyLight_ switch](https://github.com/vincentcasseau/hyStrath/wiki/How-to-::-Advanced#4-the-hylight-switch).

Thanks,

Vincent

**Comment by onurpaca** [comment]
Hi Vincent,

Thanks for the very quick response. After I made the necessary changes to tthermophysicalProperties, I was able to get the Tv fields I needed. Everything works properly right now.

Thanks,

Onur
