### ISSUE TITLE
Coud not load turbulence models

### ISSUE THREAD

**Issue by PranaykumarSingeetham** [vincentcasseau/hyStrath#27]
I was trying to run hyfoam in parallel. When I executed a command decomposePar. It is showing me the following warning:
```
 --> FOAM Warning :
From function void* Foam::dlOpen(const Foam::fileName&, bool)
in file POSIX.C at line 1321
dlopen error : /home/pranay/OpenFOAM/pranay-v1706/platforms/linux64GccDPInt32Opt/lib/libstrathTurbulenceModels.so: undefined symbol: _ZTIN4Foam15turbulenceModelE
--> FOAM Warning :
From function bool Foam::dlLibraryTable::open(const Foam::fileName&, bool)
in file db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C at line 101
could not load "libstrathTurbulenceModels.so"
```

**Comment by vincentcasseau** [comment]
Hi Pranay,  
There is not enough information to debug your case.  
1. Could you please try to run a hyFoam **tutorial** in parallel?  
2. Was your installation log file error-free?

**Comment by PranaykumarSingeetham** [comment]
Thanks. I could able to run LorrainStageI tutorial in parallel. Yes. It was installed without any errors. 
With blockMesh command, I am getting the following warning:
--> FOAM Warning : 
    From function Foam::polyMesh::polyMesh(const Foam::IOobject&, const Foam::Xfer<Foam::Field<Foam::Vector<double> > >&, const cellShapeList&, const faceListList&, const wordList&, const Foam::PtrList<Foam::dictionary>&, const Foam::word&, const Foam::word&, bool)
    in file meshes/polyMesh/polyMeshFromShapeMesh.C at line 865
    Found 22 undefined faces in mesh; adding to default patch.

Sorry, the one which I posted earlier (Could not load turbulence models warning) is encountered while checking the mesh (with checkMesh command) and the same with decomposePar as well.

**Comment by vincentcasseau** [comment]
1. This is just a warning though, not an error. It shows up because this line is in your controlDict:
`libs ("libstrathTurbulenceModels.so");`  
You only need it for the simulation but you can leave it for any stages from pre- to post-pro.

2. LorrainStageI does not need a blockMeshDict. Are you talking about your own setup? If yes, please visualise the mesh in Paraview while you are editing blockMeshDict, this will help you debugging it.

**Comment by PranaykumarSingeetham** [comment]
>     1. This is just a warning though, not an error. It shows up because this line is in your controlDict:
>        `libs ("libstrathTurbulenceModels.so");`
>        You only need it for the simulation but you can leave it for any stages from pre- to post-pro.
> 
>     2. LorrainStageI does not need a blockMeshDict. Are you talking about your own setup? If yes, please visualise the mesh in Paraview while you are editing blockMeshDict, this will help you debugging it.

Yes. It was about my own case setup. I have removed the line libs ("libstrathTurbulenceModels.so") to avoid the warning and It is fine now to continue with blockMesh without warning. 
Thanks for the help.

**Comment by niuniuniu120** [comment]
Hello, I'm interested in your hyfoam solution for ramjet engines. But I am not specialized in computational fluid research, and I have just started to learn to use open foam. Could you give me an initial setup file 0/ for reference? Because I want to try some other parameter Settings. I made a rough setting according to the parameters in the literature and your calculation results, but there was a problem in the calculated results. Could you please help me to see what documents are missing, or the setting is unreasonable? I have attached the initial 0/ file and the fina

[0.zip](https://github.com/user-attachments/files/19969428/0.zip)

l 0.0013/ file 

[0.001300000017.zip](https://github.com/user-attachments/files/19969432/0.001300000017.zip)

that I tried to set myself. Thank you very much.
