### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by tomrobin-teschner** [vincentcasseau/hyStrath#4]
Hey Vincent, 

I am currently helping someone to add your OF extension to OpenFOAM v1712 but we are both running into the same installation error, maybe you have come across it and may be able to help us out? I am using Win 10 with the Ubuntu subsystem with default gnu compilers, I have attached my logInstall and the screen output I get during the installation procedure. 

[logInstall.txt](https://github.com/vincentcasseau/hyStrath/files/1782173/logInstall.txt)
[screen_output.txt](https://github.com/vincentcasseau/hyStrath/files/1782174/screen_output.txt)

Cheers,
Tom

**Comment by vincentcasseau** [comment]
Hi Tom,

Someone emailed me today with a similar error in OF-v1712+. My reply was that the code is not supposed to be compatible with v1712+ but with v1612+ (see home page). I have not tried yet to install it in v1712+ and that was not my plan originally.

Is it vital for you (or your colleague) to use v1712+ instead of v1612+?

While I could help you to resolve this error in particular, there are chances that other will pop up later (e.g., lagrangian libraries) and this could become very time-consuming.

Thanks,
Vincent

**Comment by tomrobin-teschner** [comment]
yeah, it seems to work fine with v1612+. sorry for the extra work, i just thought that v1712 would be backward compatible. thanks for the reply.

**Comment by vincentcasseau** [comment]
Thanks for the feedback. Glad it works now.
